apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
  creationTimestamp: "2026-06-04T06:14:04Z"
  generation: 36
  labels:
    app.kubernetes.io/instance: raycluster-npu
  name: raycluster-npu-pipeline
  namespace: ray-testfieldv2
  resourceVersion: "3946931"
  uid: 21742ff2-81c1-40b4-92b3-84a346db69e8
spec:
  autoscalerOptions:
    idleTimeoutSeconds: 60
  enableInTreeAutoscaling: true
  headGroupSpec:
    rayStartParams:
      dashboard-host: 0.0.0.0
      num-cpus: "0"
    serviceType: ClusterIP
    template:
      spec:
        containers:
        - image: crpi-gcyqahoi1kzpijkb.cn-hangzhou.personal.cr.aliyuncs.com/panxy1019/panxy:ray-2.10.0-py3100-amd64
          imagePullPolicy: IfNotPresent
          name: ray-head
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "2"
              memory: 8Gi
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
        nodeSelector:
          kubernetes.io/hostname: server-00
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        volumes:
        - emptyDir: {}
          name: log-volume
  rayVersion: 2.10.0
  workerGroupSpecs:
  - groupName: npu-workers
    maxReplicas: 4
    minReplicas: 1
    numOfHosts: 1
    rayStartParams:
      resources: '"{\"NPU\": 8}"'
    replicas: 1
    scaleStrategy:
      workersToDelete: []
    template:
      metadata:
        annotations:
          ray.io/overwrite-container-cmd: "true"
          volcano.sh/network-topology-highest-tier: "1"
          volcano.sh/network-topology-mode: hard
      spec:
        containers:
        - args:
          - |
            set -e

            source /root/miniconda3/etc/profile.d/conda.sh
            conda activate ms

            if [ -f /usr/local/Ascend/driver/bin/setenv.bash ]; then
              source /usr/local/Ascend/driver/bin/setenv.bash
            fi

            source /usr/local/Ascend/cann/ascend-toolkit/set_env.sh
            source /usr/local/Ascend/cann/nnal/atb/set_env.sh

            which python
            echo "$CONDA_DEFAULT_ENV"

            ulimit -n 65536
            eval "$KUBERAY_GEN_RAY_START_CMD"
          command:
          - /bin/bash
          - -lc
          - --
          image: docker.io/library/ms_worker_daft:v2
          imagePullPolicy: IfNotPresent
          name: ray-worker
          resources:
            limits:
              cpu: "8"
              huawei.com/Ascend910: "8"
              memory: 32Gi
            requests:
              cpu: "8"
              huawei.com/Ascend910: "8"
              memory: 32Gi
          volumeMounts:
          - mountPath: /tmp/ray
            name: log-volume
          - mountPath: /usr/local/Ascend/driver
            name: ascend-driver
            readOnly: true
          - mountPath: /usr/local/dcmi
            name: ascend-dcmi
            readOnly: true
        nodeSelector:
          node.kubernetes.io/npu.chip.name: 910B3
        volumes:
        - emptyDir: {}
          name: log-volume
        - hostPath:
            path: /usr/local/Ascend/driver
          name: ascend-driver
        - hostPath:
            path: /usr/local/dcmi
          name: ascend-dcmi
status:
  availableWorkerReplicas: 1
  conditions:
  - lastTransitionTime: "2026-06-04T09:03:38Z"
    message: ""
    reason: HeadPodRunningAndReady
    status: "True"
    type: HeadPodReady
  - lastTransitionTime: "2026-06-04T06:20:50Z"
    message: All Ray Pods are ready for the first time
    reason: AllPodRunningAndReadyFirstTime
    status: "True"
    type: RayClusterProvisioned
  - lastTransitionTime: "2026-06-04T06:14:06Z"
    message: ""
    reason: RayClusterSuspended
    status: "False"
    type: RayClusterSuspended
  - lastTransitionTime: "2026-06-04T06:14:06Z"
    message: ""
    reason: RayClusterSuspending
    status: "False"
    type: RayClusterSuspending
  desiredCPU: "10"
  desiredGPU: "0"
  desiredMemory: 40Gi
  desiredTPU: "0"
  desiredWorkerReplicas: 1
  endpoints:
    client: "10001"
    dashboard: "8265"
    gcs-server: "6379"
    metrics: "8080"
    serve: "8000"
  head:
    podIP: 10.42.0.21
    podName: raycluster-npu-pipeline-head-2nchk
    serviceIP: 10.42.0.21
    serviceName: raycluster-npu-pipeline-head-svc
  lastUpdateTime: "2026-06-05T02:33:31Z"
  maxWorkerReplicas: 4
  minWorkerReplicas: 1
  observedGeneration: 36
  readyWorkerReplicas: 1
  state: ready
  stateTransitionTimes:
    ready: "2026-06-04T06:22:19Z"
